# Generated by Django 4.0.2 on 2022-02-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0004_message_alter_scholarships_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarships',
            name='feature_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
