# Generated by Django 4.0.2 on 2022-02-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0016_alter_scholarships_star'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_image', models.ImageField(blank=True, default='default/default.png', null=True, upload_to='uploads/internship/')),
                ('slug', models.SlugField(null=True, unique=True)),
                ('publisher', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('star', models.IntegerField(blank=True, null=True)),
                ('post_content', models.TextField(blank=True, null=True)),
                ('publish_date', models.CharField(blank=True, max_length=100, null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-add_date'],
            },
        ),
        migrations.AlterField(
            model_name='scholarships',
            name='feature_image',
            field=models.ImageField(blank=True, default='default/default.png', null=True, upload_to='uploads/scholarship/'),
        ),
    ]
