# Generated by Django 4.0.2 on 2022-04-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0020_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarships',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='scholarship.Tags'),
        ),
    ]
