# Generated by Django 4.0.2 on 2022-04-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0024_remove_scholarships_tag_scholarships_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarships',
            name='tag',
        ),
        migrations.AddField(
            model_name='scholarships',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='scholarship.Tags'),
        ),
    ]
