# Generated by Django 4.0.2 on 2022-05-10 14:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0025_remove_scholarships_tag_scholarships_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Updated',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('addPost', models.IntegerField(blank=True, max_length=20, null=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
