# Generated by Django 4.0.2 on 2022-05-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0026_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updated',
            name='addPost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
