# Generated by Django 4.0.2 on 2022-05-10 18:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0027_alter_updated_addpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdatedSchol',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('addPost', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.RenameModel(
            old_name='Updated',
            new_name='UpdatedIntern',
        ),
    ]
