# Generated by Django 4.0.2 on 2022-05-11 11:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0029_alter_internship_post_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
