# Generated by Django 4.0.2 on 2022-06-01 18:24

import ckeditor.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0030_alter_message_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('feature_image', models.ImageField(blank=True, default='default/default.png', null=True, upload_to='uploads/blogs/')),
                ('slug', models.SlugField(null=True, unique=True)),
                ('publisher', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('post_content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('publish_date', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
