# Generated by Django 4.0.2 on 2022-06-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0031_blog_blogtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='scholarship.BlogTag'),
        ),
    ]
