# Generated by Django 4.0.2 on 2022-02-11 14:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarships',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('publisher', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('publish_date', models.CharField(blank=True, max_length=100, null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
