# Generated by Django 4.0.2 on 2022-02-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0008_alter_scholarships_feature_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarships',
            name='feature_image',
            field=models.ImageField(blank=True, default='uploads/logos.png', null=True, upload_to=''),
        ),
    ]
