# Generated by Django 4.0.2 on 2022-02-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0013_remove_scholarships_feature_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarships',
            name='feature_image',
            field=models.ImageField(blank=True, default='default/default.png', null=True, upload_to='uploads/'),
        ),
    ]
