# Generated by Django 4.0.2 on 2022-02-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0018_subscriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='email',
            field=models.EmailField(max_length=200, null=True, unique=True),
        ),
    ]
